export enum CJoliActions {
  LOAD_TOURNEYS = "LOAD_TOURNEYS",
  SELECT_TOURNEY = "SELECT_TOURNEY",
  LOAD_RANKING = "LOAD_RANKING",
  SELECT_DAY = "SELECT_DAY",
  LOAD_TOURNEY = "LOAD_TOURNEY",
}

export enum UserActions {
  LOAD_USER = "LOAD_USER",
  COUNT_USER = "COUNT_USER",
}
